FROM node:16.20.2-bookworm

RUN mkdir -p /indexer
WORKDIR /indexer
COPY . /indexer

# Install pnpm
RUN npm install -g pnpm@6.34.0

# Build and install
RUN pnpm install --loglevel warn --frozen-lockfile --unsafe-perm
RUN pnpm run build:prod:all
